### ISSUE TITLE
Is this extension ever tested ?

### ISSUE THREAD

**Issue by MiladAlshomary** [borodulin/yii2-oauth-server#1]
I tried to use this extension on my Yii application. Each time I do a fix inside the library I got another one. A lot of errors in namespacing. Is this library still under development?
I committed out the authorization type "token" and enabled it.

**Comment by borodulin** [comment]
Implemented only authorization code. If you get error with auth code grant type, please tell me. Authorization by token I will try to do in the next day.

**Comment by MiladAlshomary** [comment]
So, can you please review my pull request and see if you can accept it. I tested it myself and the token type authorization is working.

**Comment by borodulin** [comment]
I am considering. I do not understand why you get user_id from oauth_client. I need to review rfc6749.

**Comment by borodulin** [comment]
> On the other side, implicit grant flow is for clients that implemented entirely using javascript and running in resource owner's browser.

So you should not to care about authorization.

> oauth_client - an application making protected resource requests on behalf of the resource owner and with its authorization.  The term "client" does not imply any particular implementation characteristics (e.g., whether the application executes on a server, a desktop, or other  devices).

**Comment by MiladAlshomary** [comment]
Okay I understand but in this implementation of oauth2 : https://github.com/Filsh/yii2-oauth2-server/blob/master/migrations/m140501_075311_add_oauth2_server.php

You can see that client table contains user id. Anyway if it doesn't contain user id. Where will you get the user_id for the token. By other means what does user_id mean in your implementation ?

**Comment by borodulin** [comment]
Implicit - means that user is already logged on in the browser and javascript application going to get token by ajax request. In this case user is the currently active session user.

> Client table contains user_id

I do not know. May be it is creator or last modifier...

> By other means what does user_id mean in your implementation ?

user_id - resource owner

> An entity capable of granting access to a protected resource. When the resource owner is a person, it is referred to as an end-user.

**Comment by borodulin** [comment]
user_id is linked to access, refresh tokens and to auth code, and not linked to client.

**Comment by MiladAlshomary** [comment]
That make sense. user_id should be linked with each token upon the authorization by the user. Waiting to see your update regarding the token authorization.

**Comment by borodulin** [comment]
https://github.com/borodulin/yii2-oauth2-server/pull/3 merged.
I tested with the SoupUI. Implicit grant works.
