### ISSUE TITLE
client_secret ever used for normal operation?

### ISSUE THREAD

**Issue by ebuzzz** [borodulin/yii2-oauth-server#11]
If I'm reading the code correctly, the client_secret is only used when using the refresh_token grant type. Not when using the authorization_code grant type. Is this correct? Isn't the main difference between implicit and authorization code that the requester supplies a client_secret?

**Comment by borodulin** [comment]
http://tools.ietf.org/html/rfc6749#section-4.2
The implicit grant type is used to obtain access tokens (it does not
   support the issuance of refresh tokens) and is optimized for public
   clients known to operate a particular redirection URI.  These clients
   are typically implemented in a browser using a scripting language
   such as JavaScript.

**Comment by borodulin** [comment]
Client secret is used with the Authorization Code Grant.
http://tools.ietf.org/html/rfc6749#section-4.1
The authorization code grant type is used to obtain both access tokens and refresh tokens and is optimized for confidential clients.

**Comment by borodulin** [comment]
As described in http://tools.ietf.org/html/rfc6749#section-3.2.1
client_secret (client authentication) is used for refresh_token end-point operations.
