### ISSUE TITLE
Делай минорные релизы

### ISSUE THREAD

**Issue by efureev** [borodulin/yii2-oauth-server#14]
а то исправления не учитываются в пакеджисте

**Comment by borodulin** [comment]
2 комита. один в ридми, другой - форматером по коду прошел. незачем релиз делать.

**Comment by efureev** [comment]
я про rest.

**Comment by borodulin** [comment]
это ридми

**Comment by efureev** [comment]
да у меня сегодня вылился web контроллер
=))

**Comment by efureev** [comment]
все понял. был не прав.
