### ISSUE TITLE
Need How to use DOCS

### ISSUE THREAD

**Issue by pptyasar** [borodulin/yii2-oauth-server#15]
I am planning to implement oAuth in my project. I downloaded your code but I cant understand the code.Please provide good **DOCS** for implementing yii2-oauth2-server.

**Comment by borodulin** [comment]
At the moment I do not have time to write documentation...
There are more documented library in php ported in yii, you can find them.
If you want to use OAuth2 in your project, try to understand [RFC6749](https://tools.ietf.org/html/rfc6749). I have implemented this server to add some features, that I have not found in other libraries, may be they you do not need. In any case, if you realize that you need these additional features, the questions on the documentation you will not arise.

**Comment by pptyasar** [comment]
Thanks
