### ISSUE TITLE
invalid_request   Redirect Uri is not a valid URL. 

### ISSUE THREAD

**Issue by pptyasar** [borodulin/yii2-oauth-server#16]
Redirect Uri is not a valid URL.

**Comment by borodulin** [comment]
Can you give more details about the problem?

**Comment by pptyasar** [comment]
Invalid Configuration – yii\base\InvalidConfigException
"yii\authclient\AuthAction::successCallback" should be a valid callback.

**Comment by borodulin** [comment]
I can not help with this problem.

**Comment by pptyasar** [comment]
Its all because DOCS don't have

Once I made working .

I will try to make DOCS

**Comment by borodulin** [comment]
I will be glad. Fill free to make a pull request.
