### ISSUE TITLE
'Invalid or missing response type

### ISSUE THREAD

**Issue by pptyasar** [borodulin/yii2-oauth-server#20]
exception 'conquer\oauth2\Exception' with message 'Invalid or missing response type' in C:\xampp\htdocs\project_folder\vendor\conquer\oauth2\AuthorizeFilter.php:51

Stack trace:
#0 C:\xampp\htdocs\project_folder\vendor\yiisoft\yii2\base\ActionFilter.php(75): conquer\oauth2\AuthorizeFilter->beforeAction(Object(yii\base\InlineAction))
#1 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))

**Comment by borodulin** [comment]
What's the question?
