### ISSUE TITLE
External IDPs

### ISSUE THREAD

**Issue by gaurav-singhal** [borodulin/yii2-oauth-server#45]
Hi,

We are planning to use this as oAuth server. Wanted to understand if we this can be configured to use against external IDPs? For example, 1 tenant has their users on Okta and another is on auth0. One of the client has their own internal IDP and wants to expose it through SAML. How can we support them? Can you share some sample code?

Any quick help will be highly appreciated.

Thanks!

**Comment by borodulin** [comment]
Use this extension as you wish. But I have no responsibility for what you do.
