### ISSUE TITLE
How to use the client/view files?

### ISSUE THREAD

**Issue by zhang-hang** [borodulin/yii2-oauth-server#5]
hello Borodulin,

I configured main-local.php, but shows only a blank page.

http://localhost/oauth

if (!YII_ENV_TEST) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = 'yii\debug\Module';

```
$config['bootstrap'][] = 'gii';
$config['modules']['gii']['class'] = 'yii\gii\Module';
//Add this into backend/config/main-local.php
$config['modules']['gii']['generators'] = [
    'kartikgii-crud' => ['class' => 'warrence\kartikgii\crud\Generator'],
];

$config['modules']['oauth'] = 'conquer\oauth2\Module';
```

}

Please tell me how to use it, thank you ...

**Comment by borodulin** [comment]
Hi zhang-hang!
These CRUD were generated by the conquer/gii-modal.
I recommend you not to use these CRUD, and generate your own for the conquer\oauth2\models\Client model. So, you will be able to customize access and views for your needs.

**Comment by borodulin** [comment]
But if you still want to use these CRUD, include conquer/gii-modal in you composer.json.

**Comment by zhang-hang** [comment]
Thanks for your reply,

I just quickly install yii2-oauth2-server functionality. do not want to use CRUD.

Because, see the directory has oauth2 / views / client / _form.php, create.php, index.php, view.php, update.php files. I was lazy and would like to be able to use it directly.

Ha ~ :-)

**Comment by zhang-hang** [comment]
\vendor\conquer\oauth2\views\client\index.php

conquer\gii\GiiAsset::register($this);

What does this mean? Must be used in gii in it?

**Comment by borodulin** [comment]
These assets makes the Modal dialogs functionality. You should add "conquer/gii-modal": "*" in your composer.json, then run php composer.phar update.
When you click on view or edit button link in the GridView actions column, modal dialog will be opened.

**Comment by zhang-hang** [comment]
OK, I have installed "conquer / gii-module", but still can not access   \vendor\conquer\oauth2\views\client\index.php , Only one empty page ... :8ball:

**Comment by borodulin** [comment]
I see. There is not implemented layout... 
So, just generate CRUD for the conquer\oauth2\models\Client in your application, it's a simple operation and your lazyness will not suffer. I will remove these controllers and views, to not confuse developers. There is no need to include such functionality in the extension, because views and user access depends of the business logic of the application.
